# Generated by Django 3.2.5 on 2021-08-03 13:07
import datetime

from django.db import migrations, models
import django.db.models.functions.datetime


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DevicesInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(help_text='系统', max_length=30)),
                ('model', models.CharField(help_text='型号', max_length=50)),
                ('version', models.CharField(help_text='版本', max_length=30)),
                ('propery_admin', models.CharField(help_text='资产管理员', max_length=30)),
                ('borrow_people', models.CharField(help_text='借用人', max_length=30)),
                ('desc', models.TextField(blank=True, help_text='备注')),
                ('qr_code', models.CharField(help_text='二维码', max_length=300)),
                ('ct', models.DateTimeField(default=datetime.datetime.now(), help_text='创建时间')),
                ('ut', models.DateTimeField(default=datetime.datetime.now(), help_text='更新时间')),
                ('operator', models.CharField(help_text='操作人', max_length=30)),
                ('propery_id', models.IntegerField(db_index=True, default=12345, help_text='资产id', max_length=30)),
            ],
        ),
    ]
