# Generated by Django 3.2.5 on 2021-08-04 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devicestore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicesinfo',
            name='ct',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 4, 11, 17, 39, 104217), help_text='创建时间'),
        ),
        migrations.AddField(
            model_name='devicesinfo',
            name='ut',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 4, 11, 17, 39, 104247), help_text='更新时间'),
        ),
    ]
