# Generated by Django 3.2.5 on 2021-08-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devicestore', '0002_auto_20210804_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicesinfo',
            name='ct',
        ),
        migrations.RemoveField(
            model_name='devicesinfo',
            name='ut',
        ),
        migrations.AlterField(
            model_name='devicesinfo',
            name='propery_id',
            field=models.IntegerField(db_index=True, default=12345, help_text='资产id'),
        ),
    ]
