# Generated by Django 3.2.5 on 2021-08-04 11:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('devicestore', '0003_auto_20210804_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicesinfo',
            name='ct',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间'),
        ),
        migrations.AddField(
            model_name='devicesinfo',
            name='ut',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='更新时间'),
        ),
    ]
