# Generated by Django 3.2.5 on 2021-08-04 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devicestore', '0004_auto_20210804_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicesinfo',
            name='ct',
        ),
        migrations.RemoveField(
            model_name='devicesinfo',
            name='ut',
        ),
    ]
