# Generated by Django 3.2.5 on 2021-08-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devicestore', '0006_auto_20210804_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicesinfo',
            name='propery_id',
            field=models.IntegerField(help_text='资产id', max_length=100),
        ),
    ]
