# Generated by Django 3.2.5 on 2021-08-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devicestore', '0008_devicesinfo_propery_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicesinfo',
            name='propery_id',
        ),
        migrations.AlterField(
            model_name='devicesinfo',
            name='desc',
            field=models.TextField(blank=True, help_text='备注', null=True),
        ),
        migrations.AlterField(
            model_name='devicesinfo',
            name='qr_code',
            field=models.CharField(help_text='二维码', max_length=300, null=True),
        ),
    ]
