# Generated by Django 3.2.5 on 2021-08-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devicestore', '0009_auto_20210804_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicesinfo',
            name='qr_code',
            field=models.ImageField(max_length=600,help_text='二维码', null=True, upload_to=''),
        ),
    ]
