# Generated by Django 3.2.5 on 2021-08-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devicestore', '0010_auto_20210813_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicesinfo',
            name='qr_code',
            field=models.ImageField(help_text='二维码', max_length=6000, null=True, upload_to=''),
        ),
    ]
